Upgrade bindgen to 0.65
voipir/rust-xmlsec pull request #9
Opened 2023-06-08 07:02 UTC by michabp

bindgen 0.59 doesn't work with newer clang versions.

2023-06-27 06:21 UTC, michabp commented
@lweberk if you get any time I'd appreciate it if you'd have a look at this.

Old bindgen really doesn't work with the new clang.

2023-06-30 09:22 UTC, michabp commented
@lweberk if you get any time I'd appreciate it if you'd have a look at this.

Old bindgen really doesn't work with the new clang.

2023-06-30 14:29 UTC, lweberk requested changes
Formatting cannot be removed just because it was deprecated in favor of an alternative. Otherwise we are OK

2023-06-30 14:29 UTC, lweberk commented on bindings.rs
> -            .rustfmt_bindings(true)
I'd be grateful to you if you could replace it with the non-deprecated alternative instead of straight removal

2023-06-30 16:44 UTC, lweberk commented
Closed in 21a72f0c4e9af6844e484a7842682283be99fd83, thank you for pointing this out

2023-06-30 16:44 UTC, closed without merging